blank_issues_enabled: false
contact_links:
  - name: ğŸ˜ï¸ Marketplace package feature request
    url: https://github.com/siyuan-community/ideas
    about: Request new features to the community marketplace package developers
  - name: ğŸ”€ Twitter
    url: https://twitter.com/b3logos
    about: Follow @b3logos on Twitter
